export default {
  bgPattern: require('../assets/drawer-cover.jpeg'),
  banner: require('../assets/fullBanner.jpg'),
  user: require('../assets/avatar12q.webp'),
  logo: require('../assets/logo.png'),
  step1: require('../assets/Step-1.jpg.jpeg'),
  step2: require('../assets/Step-2.jpg.jpeg'),
  step3: require('../assets/Step-3.jpg.jpeg'),
  step4: require('../assets/Step-4.jpg.jpeg'),
  step5: require('../assets/Step-5.jpg.jpeg'),
  step6: require('../assets/Step-6.jpg.jpeg'),
  step7: require('../assets/Step-7.jpg.jpeg'),
  step8: require('../assets/Step-8.jpg.jpeg'),
  step9: require('../assets/Step-9.jpg.jpeg'),
  step10V2: require('../assets/Step-10-V2.jpg.jpeg'),
  step11V2: require('../assets/Step-11-V2.jpg.jpeg'),
  step12V2: require('../assets/Step-12-V2.jpg.jpeg'),
  step13V2: require('../assets/Step-13-V2.jpg.jpeg'),
  step14V2: require('../assets/Step-14-V2.jpg.jpeg'),
  step15V2: require('../assets/Step-15-V2.jpg.jpeg'),

};
